from __future__ import annotations

from pathlib import Path


PADDLE_ENGINE = """from __future__ import annotations

from pathlib import Path
from typing import Any


try:
    from paddleocr import PaddleOCR
except Exception as exc:  # pragma: no cover - optional runtime dependency
    PaddleOCR = None
    _IMPORT_ERROR = exc
else:
    _IMPORT_ERROR = None


class PaddleOCREngine:
    def __init__(self, lang: str = "en", use_angle_cls: bool = True) -> None:
        if PaddleOCR is None:
            raise RuntimeError(
                "paddleocr is not installed in this environment. "
                "Install it inside the rewritten project before running OCR."
            ) from _IMPORT_ERROR
        self._ocr = PaddleOCR(use_angle_cls=use_angle_cls, lang=lang)

    def image_to_string(self, image: str | Path | Any) -> str:
        results = self._ocr.ocr(str(image), cls=True)
        lines: list[str] = []
        for block in results or []:
            for item in block or []:
                if len(item) >= 2 and item[1]:
                    lines.append(str(item[1][0]))
        return "\\n".join(lines).strip()


_DEFAULT_ENGINE: PaddleOCREngine | None = None


def get_engine() -> PaddleOCREngine:
    global _DEFAULT_ENGINE
    if _DEFAULT_ENGINE is None:
        _DEFAULT_ENGINE = PaddleOCREngine()
    return _DEFAULT_ENGINE


def extract_text(image: str | Path | Any) -> str:
    return get_engine().image_to_string(image)
"""


README_SNIPPET = """# PaddleOCR Rewrite

This repository copy was generated by the GitHubOCR -> PaddleOCR agent.

## What Changed

- OCR dependencies were normalized toward `paddleocr`
- A reusable wrapper was added at `migration_support/paddle_ocr_engine.py`
- A migration diff was emitted under `patches/suggested_changes.diff`

## Follow-Up

1. Install `paddleocr`
2. Validate runtime behavior with real OCR images
3. Review each transformed file before merge
"""


def write_support_files(rewritten_root: Path) -> list[Path]:
    support_dir = rewritten_root / "migration_support"
    support_dir.mkdir(parents=True, exist_ok=True)

    written = []
    engine_file = support_dir / "paddle_ocr_engine.py"
    engine_file.write_text(PADDLE_ENGINE, encoding="utf-8")
    written.append(engine_file)

    readme_file = rewritten_root / "README_PADDLE_MIGRATION.md"
    readme_file.write_text(README_SNIPPET, encoding="utf-8")
    written.append(readme_file)
    return written

